### PR TITLE
User manual

### PR DESCRIPTION
**Pull request by michaelhayashi**
Datasheet for the binary adder IC was added. Guide for end users
following proper IEEE branding was written that describes basic
operation and troubleshooting. The user manual assumes the user has
completed soldering instruction and work so that the PCB is ready for
use.

### CODE REVIEW

**Comment by michaelhayashi** [comment]
Do you think that the data sheet for the linear regulator should also be added?

**Comment by michaelhayashi** [comment]
If changes to the user manual are requested, then can be done by me ahead of the request or by _anyone else_ afterwards.

**Comment by SanayShah96** [comment]
Data sheet probably no.

**Comment by rakoskr6** [comment]
Looks good overall. Feel free to accept as is. Otherwise potential suggestions are as follows:

- Consider telling the user that during soldering it is recommended to ensure no short exists to power and ground before powering on the circuit
- Say Component smokes or catches fire is very unlikely (if it catches fire with this setup I want a video to believe it)
- Idk if you can say this linear regulator will produce substantial heat. Maybe moderate heat. Voltage drop isn't too extreme. But nbd either way

**Comment by michaelhayashi** [comment]
I will make another commit with Kyle's suggestions.

**Comment by avaidyam** [comment]
Just want to add a random comment: making a repo with branches full of workshops (and each commit is an iteration for each year/time it's put on) would be absolutely fan-fucking-tastic. 👍

**Pull request merged**
